const express = require("express")
const router = express.Router()
const userController=require("../controllers/userController")
const userJWT = require("../middleware/userJWT")
const client = require("../middleware/clientMiddleware")
const manager = require("../middleware/managerMiddleware")

router.post("/addClient",userJWT,manager,userController.addClient)
router.delete("/deleteClient",userJWT,manager,userController.deleteClient)
router.get("/getManagerClient/:id",userJWT,manager,userController.getManagerClient)
router.get("/getClient",userJWT,manager,userController.getClient)
router.put("/changePassword",userJWT,userController.changePassword)
router.post("/addManager",userController.addManager)
router.get("/getClientManagers/:id",userJWT,client,userController.getClientManagers)
router.put("/addImage",userJWT,userController.addImage)
router.get("/getProjectClients/:projectId/:managerId",userJWT,manager,userController.getProjectClients)
router.get("/getUser/:id",userJWT,userController.getUser)
router.put("/updateUser",userJWT,userController.updateUser)

module.exports=router 